version: "3.8"

services:
  mongodb:
    image: mongo:6.0
    container_name: fastapi-notes-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: notesdb

volumes:
  mongo_data:
